# Generated by Django 4.1.5 on 2023-02-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_doing'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimen',
            name='muscle_group',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
